### PR TITLE
fix building using this hacky python3.6 ppa

### PR DESCRIPTION
**Pull request by eklitzke**

### CODE REVIEW

**Comment by jmphilli** [comment]
Hmmmm looks like it didn't compile against the right archive / so

**Comment by jmphilli** [comment]
In my compile process I see it compile against three... I get three archives out of it...

**Comment by jmphilli** [comment]
This is basically what I started with ... check for the python 3.6 package in configure.ac

**Comment by eklitzke** [comment]
See https://github.com/uber/pyflame/issues/69#issuecomment-314697390

**Pull request closed without merging**
