### PR TITLE
feat(pyfrob) let user set python version

### PR DESCRIPTION
**Pull request by mmr**
The python version auto detection fails in some scenarios

**Example**: when trying to trace a `uWSGI` (python app server) process

This PR lets the user explicitly choose the version while the
detection is fixed

How to use it:
```bash
# For python 2:
pyflame --python 2 ...

# For python 3:
pyflame --python 3 ...

# Or use the shorter form:
pyflame -p2 ...
pyflame -p3 ...
```

To be able to use `-p2` or `-p3` pyflame has to be compiled with `ENABLE_PY2` and/or `ENABLE_PY3` respectively

### CODE REVIEW

**Comment by eklitzke** [comment]
This looks good to me! I just merged another PR that conflicts with this. Could you rebase?

**Comment by eklitzke** [comment]
Can you also squash your commits when you rebase?

**Comment by mmr** [comment]
There @eklitzke, merged and refactored a bit
About the squashing, isn't it better to squash on merge?

**Comment by eklitzke** [comment]
AFIAK if you do `git merge --squash` it merely stages the changes, which would mean the commit would lose your authorship information. If you squash the commits in your branch then I can merge it where the change is still attributed to you.

**Comment by mmr** [comment]
Oh, I get it @eklitzke 
What about the `merge & squash` feature in github?
I think it retains authorship

**Pull request merged**
