### PR TITLE
Add an optional output to a file

### PR DESCRIPTION
**Pull request by abeutot**
So that when we run in trace mode, profiler and program outputs don't
get mixed up.

### CODE REVIEW

**Comment by akatrevorjay** [comment]
A better solution is to properly use stderr and stdout imo

**Comment by eklitzke** [comment]
I am on board with this change, but:
 * You will need to sign the Uber CLA
 * Please run the code through clang-format, I see at least one style violation

**Comment by eklitzke** [comment]
@akatrevorjay I think this is legitimate. The issue (which I've run into as well) is that when using `pyflame -t` the stdout from Pyflame is the same as the stdout for the child process (and likewise Pyflame has the same stderr as the child process). Thus the profiling data from the subprocess is interleaved with the stdout of the child.

Another way to do this would be to use `dup2(2)` to move stdout to another file descriptor number, and then the user could redirect that file descriptor to a file, e.g. you could imagine something like:

    pyflame --fd 99 -t python foo.py 99>profile.txt

This is similar to how `flock(1)` works, but I think it's more esoteric since fewer people know how to redirect arbitrary file descriptors.

Anyway, sign the CLA and we can get this merged.

**Comment by abeutot** [comment]
I ran clang-format so now it should be fine.

(As a side effect it also updated the CLA status.)

**Pull request merged**
